name: Daily Post
on:
  schedule:
    - cron: "00 18 * * *" # Runs at 18:00 UTC daily
  workflow_dispatch: # Optional: Manual trigger on Github

jobs:
  permissions:
    contents: write # Allow the workflow to write to the repository
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          X_BEARER_TOKEN: ${{ secrets.X_BEARER_TOKEN }}
          X_API_KEY: ${{ secrets.X_API_KEY }}
          X_API_KEY_SECRET: ${{ secrets.X_API_KEY_SECRET }}
          X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
          X_ACCESS_TOKEN_SECRET: ${{ secrets.X_ACCESS_TOKEN_SECRET }}
          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
        run: python scheduled_twitter_bot.py # main script name
      - name: Commit and push changes
        if: sucess() # Only run if the previous step was successful
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add data.json
          git commit -m "Daily update"
          git push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub token for authentication
