name: Daily Post
on:
  schedule:
    - cron: "0 21 * * *" # Runs at 12:00 UTC daily (adjust timezone as needed)
  workflow_dispatch: # Optional: Manual trigger

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install python-dotenv tweepy cloudinary

      - name: Create .env file
        run: |
          cat << EOF > .env
          # Twitter/X API
          X-BEARER_TOKEN=${{ secrets.X_BEARER_TOKEN }}
          X-API_KEY=${{ secrets.X_API_KEY }}
          X-API_KEY_SECRET=${{ secrets.X_API_KEY_SECRET }}
          X-ACCESS_TOKEN=${{ secrets.X_ACCESS_TOKEN }}
          X-ACCESS_TOKEN_SECRET=${{ secrets.X_ACCESS_TOKEN_SECRET }}

          # Cloudinary
          CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}
          EOF

      - name: Run Hemeroteca Bot
        run: python bot.py # Or your main script name
